"""add until_target to simulation_runs

Revision ID: 01be612f1e22
Revises: a738e8e522d3
Create Date: 2026-09-24 01:47:14.002405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01be612f1e22'
down_revision: Union[str, None] = 'a738e8e522d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('until_target', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'until_target')
    # ### end Alembic commands ###
