"""add seed to simulation_runs

Revision ID: 891fb8be331c
Revises: 695c06727c20
Create Date: 2026-09-24 00:48:34.903137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '891fb8be331c'
down_revision: Union[str, None] = '695c06727c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('seed', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'seed')
    # ### end Alembic commands ###
