"""add spec_snapshot to simulation_runs

Revision ID: a738e8e522d3
Revises: 891fb8be331c
Create Date: 2026-09-24 01:25:47.531673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a738e8e522d3'
down_revision: Union[str, None] = '891fb8be331c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('spec_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'spec_snapshot')
    # ### end Alembic commands ###
